---
title: "North Carolina Well Water Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: bootstrap
---

```{r setup, include=FALSE}
library(crosstalk)
library(plotly)
library(flexdashboard)
library(leaflet)
library(sf)
library(here)
library(DT)
library(dplyr)
library(sp)
sf <- st_read(here("data/NCBG84.gpkg"))
sfSel <- sf%>%
  select(GISJOIN,Hybd_Tot_10,Population,Pop_Served,County,Name)
spSel <- as(sfSel,"Spatial")

# Create different shared objects for the table and the map
sd_map <- SharedData$new(spSel)
sd_df <- SharedData$new(as.data.frame(spSel@data), group = sd_map$groupName())

```

Column {data-width=350}
-----------------------------------------------------------------------

### Filters

```{r filters}
#Create crosstalk filters using sd_df:

filter_select("filterid",
    "County",
    sd_df,
    ~County)

filter_slider(
    id = "Popid",
    label = "Total Population",
    sharedData = sd_df,
    column = ~Population,
    step = 100,
    round = TRUE,
    sep = "",
    ticks = FALSE
  )
```

### Table

```{r dt}
sd_df%>%
  datatable()
```

Column {data-width=650}
-----------------------------------------------------------------------

### Map

```{r leaflet}
sd_map%>%
leaflet()%>%
  addTiles()%>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
              fillColor = ~colorQuantile("YlOrRd", Hybd_Tot_10)(Hybd_Tot_10),
              highlightOptions = highlightOptions(color = "white", weight = 2,
                                                  bringToFront = TRUE))
```

### Plot

```{r plotly}
sd_df%>%
  plot_ly()%>%
  add_markers(x=~Population,y=~Hybd_Tot_10,color=~County)
```

